
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 15000
        min-idle: 14000
        max-wait: 1000
    password:
    timeout: 1000


# mybatis
# 对应实体类的包名
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

